FIND_PATH(
  ASSIMP_INCLUDE_DIRS
  NAMES postprocess.h scene.h version.h config.h cimport.h
  HINTS
  PATH_SUFFIXES include/assimp include
  PATHS /usr/local/include/
)

FIND_LIBRARY(
  ASSIMP_LIBRARIES
  NAMES assimp
  PATH_SUFFIXES lib
  PATHS /usr/local/lib/
)

IF (ASSIMP_INCLUDE_DIRS AND ASSIMP_LIBRARIES)
  SET(ASSIMP_FOUND TRUE)
ENDIF (ASSIMP_INCLUDE_DIRS AND ASSIMP_LIBRARIES)

IF (ASSIMP_FOUND)
  IF (NOT ASSIMP_FIND_QUIETLY)
    MESSAGE(STATUS "Found asset importer library: ${ASSIMP_LIBRARIES}")
  ENDIF (NOT ASSIMP_FIND_QUIETLY)
ELSE (ASSIMP_FOUND)
  IF (ASSIMP_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find asset importer library")
  ENDIF (ASSIMP_FIND_REQUIRED)
ENDIF (ASSIMP_FOUND)